Update pipeline (ignore)

diff --git a/pipeline (ignore) b/pipeline (ignore)
--- a/pipeline (ignore)
+++ b/pipeline (ignore)
@@ -34,3 +34,58 @@ pipeline {
         }
     }
 }
+
+
+
+
+
+__________________________________________V2 _______________________________________________________
+pipeline {
+    agent any
+
+    stages {
+        stage('Clone Repository') {
+            steps {
+                git 'https://github.com/ManishReal01/Python_router_automation.git'
+            }
+        }
+        stage('Setup Python Environment') {
+            steps {
+                sh '''
+                # Check if python3 is installed
+                if ! command -v python3 &> /dev/null
+                then
+                    echo "Python3 could not be found, installing..."
+                    sudo apt-get update
+                    sudo apt-get install -y python3 python3-pip
+                fi
+
+                # Install virtualenv if not installed
+                if ! pip3 show virtualenv &> /dev/null
+                then
+                    echo "virtualenv could not be found, installing..."
+                    sudo apt-get install -y python3-virtualenv
+                fi
+
+                # Create and activate virtual environment
+                python3 -m venv venv
+                . venv/bin/activate
+
+                # Install required packages
+                pip install netmiko
+                '''
+            }
+        }
+        stage('Run Script') {
+            steps {
+                sh '''
+                # Activate virtual environment
+                . venv/bin/activate
+
+                # Run your Python script
+                python router_automation_test.py
+                '''
+            }
+        }
+    }
+}
